### ISSUE TITLE
Stops reporting metrics if a database is removed

### ISSUE THREAD

**Issue by benwh** [rnaveiras/postgres_exporter#49]
After a database is removed, the exporter seems to no longer return _any_ metrics.

```
level=error ts=2020-05-22T10:17:02.334305763Z caller=exporter.go:121 error="failed to connect to `host=/var/run/postgresql user=postgres database=optimus`: server error (FATAL: database \"optimus\" does not exist (SQLSTATE 3D000))"
```

A restart of the exporter process fixes this. Without looking at the code I'm guessing that the list of databases to probe is cached at startup.

cc @rnaveiras

**Comment by rnaveiras** [comment]
Yep, you're correct, it only that discover of databases on bootstrap.
